services:
  postgres:
    container_name: grades.database
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: studentsgrades
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5433:5433
    volumes:
        - postgres-data:/var/lib/posgtres/data

volumes:
    postgres-data:    